server:
  port: 8080

database:
  postgresdb:
    dbhost: "localhost"
    dbport: 5432
    dbname: "awepods"
    dbuser: "postgres"
    dbpassword: "postgres"
  mongodb:
    dbhost: "localhost"
    dbport: 27017
    dbname: "awepods"
    dbuser: "mongodb"
    dbpassword: "mongodb"

